### ISSUE TITLE
Fatal Exception: java.util.NoSuchElementException

### ISSUE THREAD

**Issue by mateuszkwiecinski** [otwarty-wykop-mobilny/wykop-android#84]
```
Fatal Exception: java.util.NoSuchElementException: Key interface wb.b (Kotlin reflection is not available) is missing in the map.
       at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapsKt__MapWithDefaultKt.java:24)
       at kotlin.collections.MapsKt__MapsKt.getValue(MapsKt__MapsKt.java:344)
       at kotlin.collections.MapsKt.getValue(MapsKt.java)
       at io.github.wykopmobilny.WykopApp.launchScoped(WykopApp.java:204)
       at io.github.wykopmobilny.ui.base.AppScopes$DefaultImpls.launchScoped$default(AppScopes.java:14)
       at io.github.wykopmobilny.domain.search.GetSearchDetailsQuery$searchResultsFlow$2$1$1.invoke(GetSearchDetailsQuery.java:70)
       at io.github.wykopmobilny.domain.search.GetSearchDetailsQuery$searchResultsFlow$2$1$1.invoke(GetSearchDetailsQuery.java:60)
       at io.github.wykopmobilny.ui.modules.search.SearchFragment$onCreateOptionsMenu$1$1$1.invokeSuspend(SearchFragment.java:74)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:104)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoopImplBase.java:274)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:85)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__BuildersKt.java:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(BuildersKt.java:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(BuildersKt__BuildersKt.java:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(BuildersKt.java:1)
       at io.github.wykopmobilny.ui.modules.search.SearchFragment.onCreateOptionsMenu$lambda-2$lambda-1(SearchFragment.java:74)
       at io.github.wykopmobilny.ui.modules.search.SearchFragment.$r8$lambda$H50KXyIFr6ge8ij_8xEWO8A8O3E(SearchFragment.java)
       at io.github.wykopmobilny.ui.modules.search.SearchFragment$$InternalSyntheticLambda$0$5eb42e0b76a94504c3e17f9c51866683b3932e1c0b06e3182e6ab6bcbebf00a3$0.onItemClick(SearchFragment.java:8)
       at android.widget.AutoCompleteTextView.performCompletion(AutoCompleteTextView.java:1071)
       at android.widget.AutoCompleteTextView.access$600(AutoCompleteTextView.java:101)
       at android.widget.AutoCompleteTextView$DropDownItemClickListener.onItemClick(AutoCompleteTextView.java:1414)
       at android.widget.AdapterView.performItemClick(AdapterView.java:330)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1187)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3179)
       at android.widget.AbsListView$3.run(AbsListView.java:4097)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
       ```

**Comment by mateuszkwiecinski** [comment]
Fixed in https://github.com/otwarty-wykop-mobilny/wykop-android/pull/100
